In [97]:
import numpy as np
arr = np.array([[1,2,3,4],
                [2,2,3,4],
                [1,2,3,4],])
print(arr)
arr

[[1 2 3 4]
 [2 2 3 4]
 [1 2 3 4]]


array([[1, 2, 3, 4],
       [2, 2, 3, 4],
       [1, 2, 3, 4]])

In [98]:
type(arr)

numpy.ndarray

In [99]:
arr.shape

(3, 4)

In [100]:
arr.ndim

2

In [101]:
narr = arr.reshape(6,2)
narr

array([[1, 2],
       [3, 4],
       [2, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [102]:
narr = narr.reshape(-1)
narr

array([1, 2, 3, 4, 2, 2, 3, 4, 1, 2, 3, 4])

In [103]:
narr.shape

(12,)

In [104]:
arr[0][0]


1

In [105]:
arr[1,3]

4

In [106]:
for x in arr:
    print(x)

[1 2 3 4]
[2 2 3 4]
[1 2 3 4]


In [107]:
for x in arr:
    for y in x:
        print(y)

1
2
3
4
2
2
3
4
1
2
3
4


In [108]:
arr[1][::-1]

array([4, 3, 2, 2])

In [109]:
print(narr)
narr = np.where(narr % 2 == 0)
narr # it give index position 

[1 2 3 4 2 2 3 4 1 2 3 4]


(array([ 1,  3,  4,  5,  7,  9, 11], dtype=int64),)

In [113]:
arr2 = np.array(['rApple', 'bana', 'happ', 'o2'])
arr2 = np.sort(arr2)
arr2

array(['bana', 'happ', 'o2', 'rApple'], dtype='<U6')